// ignore: unused_import
import 'package:intl/intl.dart' as intl;
import 'app_localizations.dart';

// ignore_for_file: type=lint

/// The translations for English (`en`).
class AppLocalizationsEn extends AppLocalizations {
  AppLocalizationsEn([String locale = 'en']) : super(locale);

  @override
  String get appName => 'AI-Spy';

  @override
  String get waitingText => 'Our goofy friend is waiting for your photo...';

  @override
  String get scanningText => 'Scanning pixels... sweat is dropping...';

  @override
  String get dropPhotoTitle => 'Drop it in the Truth Machine';

  @override
  String get choosePhoto => 'Choose Photo';

  @override
  String get takePicture => 'Take a Picture';

  @override
  String get fakeAlertTitle => '🚨 FAKE ALERT!';

  @override
  String get organicTitle => '✅ 100% ORGANIC';

  @override
  String get confidencePrefix => 'Guabao\'s Confidence';

  @override
  String get fakeDescription =>
      'Wow. Someone is trying to pull a fast one. We detected heavy AI-generated artifacts in this image.';

  @override
  String get realDescription =>
      'You can sleep well tonight. This image was captured by a real human in the real world.';

  @override
  String get unlockReportTitle => 'Unlock Deep Analysis Report';

  @override
  String get unlockReportDesc =>
      'See exactly which pixels were generated by Midjourney/Stable Diffusion.';

  @override
  String get revealTruthBtn => 'Reveal Truth for ¥4.9';

  @override
  String get shareVerdict => 'Share Verdict';

  @override
  String get scanAnother => 'Scan Another Photo';

  @override
  String get historyTitle => 'History';

  @override
  String get historyLocalDisclaimer => 'History is stored only on this device.';

  @override
  String get restorePurchases => 'Restore Purchases';

  @override
  String get appVersionLabel => 'AI-Spy MVP v1.0\nBuilt for truth.';

  @override
  String get readyNextScan => 'Ready for the next scan!';

  @override
  String get backendError => 'Backend Error:';

  @override
  String get fakeToast => '🔥 FAKE ALERT! High AI Probability! 🔥';

  @override
  String get realToast => '✅ Pure natural origin confirmed!';

  @override
  String get restoreSuccessToast => '✅ Purchases Restored Successfully!';

  @override
  String get mockIapUnlockedToast => 'Mock IAP: Unlocked! ✨';

  @override
  String get historyTimeJustNow => 'Just Now';

  @override
  String get historyTime2Hrs => '2 hrs ago';

  @override
  String get historyTimeYesterday => 'Yesterday';
}
